#!/bin/sh

# https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html
mkdir -p /usr/local/src
cd /usr/local/src

# clone suckless programs
git clone https://git.suckless.org/dwm
git clone https://git.suckless.org/st
git clone https://git.suckless.org/scroll

# dwm patches
mkdir dwm/patches && cd dwm/patches
wget https://dwm.suckless.org/patches/alpha/dwm-fixborders-6.2.diff
wget https://dwm.suckless.org/patches/hide_vacant_tags/dwm-hide_vacant_tags-6.2.diff
wget https://dwm.suckless.org/patches/statusallmons/dwm-statusallmons-6.2.diff
cd ../..

# st patches
mkdir st/patches && cd st/patches
wget https://st.suckless.org/patches/anysize/st-anysize-0.8.1.diff
cd ../..
