# ~/.config/alacritty/alacritty.yml
#
# see /usr/share/doc/alacritty/example/alacritty.yml

window:
  opacity: 0.8

  padding:
    x: 5
    y: 5

  dynamic_padding: true

font:
  normal:
    family: "Terminus (TTF)"
    style: Regular

  bold:
    family: "Terminus (TTF)"
    style: Bold

  italic:
    family: "Terminus (TTF)"
    style: Italic

  bold_italic:
    family: "Terminus (TTF)"
    style: Bold Italic

  size: 8.5

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: '#282828'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'

key_bindings:
  - { key: Return, mods: Control|Alt, action: SpawnNewInstance }
  - { key: L,      mods: Control|Alt, action: ResetFontSize    }
  - { key: K,      mods: Control|Alt, action: IncreaseFontSize }
  - { key: J,      mods: Control|Alt, action: DecreaseFontSize }
