# ~/.config/alacritty/alacritty.yml
#
# see /usr/share/doc/alacritty/example/alacritty.yml

window:
  opacity: 1

  padding:
    x: 5
    y: 5

  dynamic_padding: true

font:
  normal:
    family: "Terminus (TTF)"
    style: Regular

  bold:
    family: "Terminus (TTF)"
    style: Bold

  italic:
    family: "Terminus (TTF)"
    style: Italic

  bold_italic:
    family: "Terminus (TTF)"
    style: Bold Italic

  size: 9.5

colors:
  primary:
    background: '#1e1e1e'
    foreground: '#cccccc'

  selection:
    text: "#404040"
    background: "#d4d4d4"

  normal:
    black:   "#000000"
    red:     "#cd3131"
    green:   "#0dbc79"
    yellow:  "#e5e510"
    blue:    "#2472c8"
    magenta: "#bc3fbc"
    cyan:    "#11a8cd"
    white:   "#e5e5e5"

  bright:
    black:   "#666666"
    red:     "#f14c4c"
    green:   "#23d18b"
    yellow:  "#f5f543"
    blue:    "#3b8eea"
    magenta: "#d670d6"
    cyan:    "#29b8db"
    white:   "#e5e5e5"

key_bindings:
  - { key: Return, mods: Control|Alt, action: SpawnNewInstance }
  - { key: L,      mods: Control|Alt, action: ResetFontSize    }
  - { key: K,      mods: Control|Alt, action: IncreaseFontSize }
  - { key: J,      mods: Control|Alt, action: DecreaseFontSize }
