# ~/.config/alacritty/alacritty.yml
#
# see /usr/share/doc/alacritty/example/alacritty.yml

window:
  opacity: 1

  padding:
    x: 5
    y: 5

  dynamic_padding: true

font:
  normal:
    family: "Terminus (TTF)"
    style: Regular

  bold:
    family: "Terminus (TTF)"
    style: Bold

  italic:
    family: "Terminus (TTF)"
    style: Italic

  bold_italic:
    family: "Terminus (TTF)"
    style: Bold Italic

  size: 8.5

colors:
  primary:
    background: '#ebeaf2'
    foreground: '#004f7c'
  cursor:
    text:   '#ffffff'
    cursor: '#171421'

  normal:
    black:   "#003B4E"
    red:     "#E64569"
    green:   "#069F5F"
    yellow:  "#DAB752"
    blue:    "#439ECF"
    magenta: "#D961DC"
    cyan:    "#00B1BE"
    white:   "#B3B3B3"

  bright:
    black:   "#3E89A1"
    red:     "#E4859A"
    green:   "#A2CCA1"
    yellow:  "#E1E387"
    blue:    "#6FBBE2"
    magenta: "#E586E7"
    cyan:    "#96DCDA"
    white:   "#DEDEDE"

key_bindings:
  - { key: Return, mods: Control|Alt, action: SpawnNewInstance }
  - { key: L,      mods: Control|Alt, action: ResetFontSize    }
  - { key: K,      mods: Control|Alt, action: IncreaseFontSize }
  - { key: J,      mods: Control|Alt, action: DecreaseFontSize }
