# ~/.config/alacritty/alacritty.yml
#
# see /usr/share/doc/alacritty/example/alacritty.yml

window:
  opacity: 0.9

  padding:
    x: 1
    y: 1

  dynamic_padding: true

font:
  normal:
    family: "DejaVuSansMono"
    style: Regular

  bold:
    family: "DejaVuSansMono"
    style: Bold

  italic:
    family: "DejaVuSansMono"
    style: Italic

  bold_italic:
    family: "DejaVuSansMono"
    style: Bold Italic

  size: 7

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: '#282828'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'

key_bindings:
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance   }
  - { key: Plus,   mods: Control|Shift, action: IncreaseFontSize   }
  - { key: Minus,  mods: Control,       action: DecreaseFontSize   }
  - { key: Equals, mods: Control,       action: ResetFontSize      }
  - { key: K,      mods: Control|Shift, action: ScrollLineUp       }
  - { key: J,      mods: Control|Shift, action: ScrollLineDown     }
  - { key: U,      mods: Control|Shift, action: ScrollHalfPageUp   }
  - { key: D,      mods: Control|Shift, action: ScrollHalfPageDown }
