# ~/.config/alacritty/alacritty.yml
#
# see /usr/share/doc/alacritty/example/alacritty.yml

window:
  opacity: 0.9

  padding:
    x: 2
    y: 2

  dynamic_padding: true

font:
  normal:
    family: "Hack"
    style: Regular

  bold:
    family: "Hack"
    style: Bold

  italic:
    family: "Hack"
    style: Italic

  bold_italic:
    family: "Hack"
    style: Regular

  size: 7

colors:

  # Default colors
  primary:
    background: '#1e1e1e'
    foreground: '#cccccc'


  selection:
    text: '#d4d4d4'
    background: '#404040'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#cd3131'
    green:   '#0dbc79'
    yellow:  '#e5e510'
    blue:    '#2472c8'
    magenta: '#bc3fbc'
    cyan:    '#11a8cd'
    white:   '#e5e5e5'

  # Bright colors
  bright:
    black:   '#666666'
    red:     '#f14c4c'
    green:   '#23d18b'
    yellow:  '#f5f543'
    blue:    '#3b8eea'
    magenta: '#d670d6'
    cyan:    '#29b8db'
    white:   '#e5e5e5'

key_bindings:
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance   }
  - { key: Plus,   mods: Control|Shift, action: IncreaseFontSize   }
  - { key: Minus,  mods: Control,       action: DecreaseFontSize   }
  - { key: Equals, mods: Control,       action: ResetFontSize      }
  - { key: K,      mods: Control|Shift, action: ScrollLineUp       }
  - { key: J,      mods: Control|Shift, action: ScrollLineDown     }
