if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf.vim'
Plug 'chrisbra/colorizer'
call plug#end()

filetype indent plugin on
syntax on
set hlsearch
set ignorecase
set smartcase
set number relativenumber
set tabstop=2
set shiftwidth=2
set expandtab
set laststatus=2

" remove trailing whitespaces
au BufWritePre * %s/\s\+$//e

" underline spell errors
hi clear SpellBad
hi SpellBad cterm=underline ctermbg=none ctermfg=red

" better preview window
set splitbelow
au InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif

" golang
au FileType go set expandtab&

" bindings
let mapleader=","
let maplocalleader="\<Space>"
nnoremap <leader><leader> :Files<CR>
nnoremap <leader>. :Buffers<CR>
nnoremap <leader>s :set spell!<CR>
nnoremap <leader>e :set spelllang=es<CR>
nnoremap <leader>i :set spelllang=en<CR>
nnoremap <leader>c :!pdflatex -halt-on-error --shell-escape %<CR>
nnoremap <leader>p :!zathura %:r.pdf &<CR>
