if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf.vim'
Plug 'chrisbra/colorizer'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'yggdroot/indentline'
call plug#end()

filetype indent plugin on
syntax on
set hlsearch
set ignorecase
set smartcase
set nowrap
set number relativenumber
set tabstop=4
set shiftwidth=4
set expandtab
colorscheme desert

" remove trailing whitespaces
au BufWritePre * %s/\s\+$//e

" underline spell errors
hi clear SpellBad
hi SpellBad cterm=underline ctermbg=none ctermfg=red

" better preview window
set splitbelow
au InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif

" golang
au FileType go set expandtab&
let g:go_play_browser_comand="$BROWSER %URL% &"

" indentline
let g:indentLine_char='>'
let g:indentLine_leadingSpaceEnabled=1
let g:indentLine_leadingSpaceChar='-'

" gruvbox
let g:gruvbox_termcolors=16

" bindings
let mapleader=","
let maplocalleader="\<Space>"
nnoremap <leader><leader> :Files<CR>
nnoremap <leader>. :Buffers<CR>
nnoremap <leader>s :set spell!<CR>
nnoremap <leader>e :set spelllang=es<CR>
nnoremap <leader>i :set spelllang=en<CR>
nnoremap <leader>c :!pdflatex -halt-on-error --shell-escape %<CR>
