wal.sh
dunst &
xcompmgr &
clipmanagerd &

switch\
    -i\
    'pactl subscribe'\
    'acpi_listen'\
    'udevadm monitor --udev --property'\
    'time.sh'\
    -o\
    'statusbar.awk'\
    'lowbat.awk'\
    'notify.awk'\
    -r\
    1-1 2-1 3-1 4-1\
    1-2 2-2 3-2 4-2\
    1-3 2-3 3-3 4-3 &

dbus-launch --sh-syntax --exit-with-session
source /etc/X11/xinit/xinitrc.d/80-dbus.sh
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

exec dwm
