#!/bin/sh

wal.sh &
dunst &
xcompmgr &

switch\
    -i\
    'pactl subscribe'\
    'acpi_listen'\
    'udevadm monitor --udev --property'\
    'time.sh'\
    -o\
    'statusbar.awk'\
    'lowbat.awk'\
    -r\
    1-1 2-1 3-1 4-1\
    1-2 2-2 3-2 4-2 &

# Levantar bus de usuario dbus.
source /etc/X11/xinit/xinitrc.d/80-dbus.sh

# Levantar ssh-agent de gcr usando mi script, requerido por gnome-keyring ssh.
eval $(start-gcr-ssh-agent)
export SSH_AUTH_SOCK

# Gnome keyring se inicializa en dos pasos:
#
# Primero pam ejecuta gnome-keyring-daemon con --login por parte de pam lo que permite desbloquear el keyring en el login.
# Luego se llama a gnome-keyring-daemon con --start lo que lo termina de inicializar.

# Setear variable de entorno GNOME_KEYRING_CONTROL, el modulo de pam lo deberia hacer pero no funciona.
export GNOME_KEYRING_CONTROL=/run/user/$(id -u)/keyring

# Inicializar daemon de keyring creado por pam, requiere variable GNOME_KEYRING_CONTROL y SSH_AUTH_SOCK.
gnome-keyring-daemon --start --components=secrets,ssh

exec dwm
