# for zsh install as ~/.zprofile

# programs
export EDITOR=nvim
export BROWSER=firefox
export READER=zathura
export VIEWER=sxiv
export PLAYER=mpv
export TERMINAL=alacritty

# xdg
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# https://wiki.archlinux.org/index.php/XDG_Base_Directory#Partial
export LESSHISTFILE='-'
export GOPATH="$XDG_DATA_HOME"/go
alias wget="wget --hsts-file=$XDG_CACHE_HOME/wget-hsts"

# fix java apps
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit

# pacdiff editor
export DIFFPROGRAM=$EDITOR

# android
export ANDROID_HOME=~/Android/Sdk

# path
export PATH=$PATH:~/bin
export PATH=$PATH:~/scripts
export PATH=$PATH:~/.local/bin
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/lib/rstudio
export PATH=$PATH:$HOME/.opam/default/bin
export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/emulator

# opam ocaml
command -v opam 2>&1 >/dev/null && eval $(opam env)
