# for zsh install as ~/.zprofile

export EDITOR=nvim
export BROWSER=firefox
export READER=zathura
export VIEWER=sxiv
export PLAYER=mpv
export TERMINAL=alacritty

# xdg
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# https://wiki.archlinux.org/index.php/XDG_Base_Directory#Partial
export LESSHISTFILE='-'
export GOPATH="$XDG_DATA_HOME"/go
alias wget="wget --hsts-file=$XDG_CACHE_HOME/wget-hsts"
alias yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config"

# fix java apps
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit

# pacdiff editor
export DIFFPROGRAM=$EDITOR

# path
export PATH=$PATH:~/bin
export PATH=$PATH:~/.local/bin
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:~/.local/share/gem/ruby/3.0.0/bin

export ANDROID_HOME=$HOME/Downloads/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# runit
export SVDIR=/etc/runit/runsvdir/current/

# Gestor de npm para ubuntu.
if [ -e "$HOME/.nvm" ]
then
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
fi

# ghc
[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env"

# opam: ocaml install, coq install, etc.
if [ -e "$HOME/.opam/default/bin" ]
then
    export PATH="$PATH:$HOME/.opam/default/bin"
fi
