# add to path
export PATH=$PATH:~/.local/bin
export PATH=$PATH:~/.local/bin/scripts

# programs
export EDITOR=vim
export BROWSER=icecat
export READER=zathura
export VIEWER=sxiv
export PLAYER=mpv
export TERMINAL=st
export OPENER=open

# xdg
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# less bloated home dir
export LESSHISTFILE='-'
export GOPATH="$XDG_DATA_HOME"/go

# add go binaries to path
export PATH=$PATH:$GOPATH/bin
