autoload -Uz vcs_info
precmd_vcs_info() {
    vcs_info
}
precmd_functions+=( precmd_vcs_info )
zstyle ':vcs_info:git:*' formats '%b'

autoload -U colors && colors

setopt prompt_subst

PROMPT="%B%{$fg[default]%}%d%b"$'\n'"%# "
RPROMPT="%B%{$fg[default]%}\$vcs_info_msg_0_%b"

autoload -Uz compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect '^[' vi-cmd-mode

HISTSIZE=10000
SAVEHIST=10000
mkdir -p ~/.cache/zsh
HISTFILE=~/.cache/zsh/history

bindkey -v

# beam cursor insert mode

zle-keymap-select() {
    case $KEYMAP in
        vicmd) echo -ne '\e[1 q';;
        viins|main) echo -ne '\e[5 q';;
    esac
}
zle -N zle-keymap-select

zle-line-init() {
    zle -K viins
    echo -ne '\e[5 q'
}
zle -N zle-line-init

preexec() {
    echo -ne '\e[1 q'
}

alias ls='ls --color=auto --group-directories-first'
alias rm='rm -i'
alias su='sudo -i'
alias grep='grep --color=auto'
alias v="$EDITOR"
alias c=clear
alias l=ls
alias la='ls -a'
alias ll='ls -la'
alias d=cd
alias e=exit

lfcd() {
    tmp="$(mktemp)"
    lf -last-dir-path="$tmp"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        if [ -d "$dir" ]; then
            if [ "$dir" != "$(pwd)" ]; then
                cd "$dir"
            fi
        fi
    fi
}

newst() {
    st -e 'zsh' &
    disown
}

bindkey -s '^o' 'lfcd\n'
bindkey -s '^n' 'newst\n'

# zsh-users plugins
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh 2>/dev/null &&
  bindkey '^H' history-substring-search-up &&
  bindkey '^L' history-substring-search-down
