#!/bin/sh

fifos="$(mktemp -d)"

mkfifo "$fifos/dwmbar_pactl"
mkfifo "$fifos/dwmbar_acpi"
mkfifo "$fifos/dwmbar_udevadm"
mkfifo "$fifos/dwmbar_seconds"
mkfifo "$fifos/notify_udevadm"

remove_files() {
    rm -rf "$fifos"
}

trap 'remove_files' 0 1 2 3 6 9 14 15

udevadm monitor --udev --property | tee "$fifos/dwmbar_udevadm" "$fifos/notify_udevadm" >/dev/null &
pactl subscribe > "$fifos/dwmbar_pactl" &
acpi_listen > "$fifos/dwmbar_acpi" &
( while true; do date '+%H %M %S'; sleep 1; done ) > "$fifos/dwmbar_seconds" &

(
    cat "$fifos/dwmbar_pactl" &
    cat "$fifos/dwmbar_acpi" &
    cat "$fifos/dwmbar_udevadm" &
    cat "$fifos/dwmbar_seconds" &
) | dwmbar.awk &

cat "$fifos/notify_udevadm" | notify.awk
