#!/bin/sh

fifos="$(mktemp -d)"
mkfifo "$fifos/fifo1"
mkfifo "$fifos/fifo2"
mkfifo "$fifos/fifo3"

cleanup() {
    rm -rf "$fifos"
    for x in $(jobs -p)
    do
        kill "$x"
    done
}

trap cleanup INT QUIT TERM EXIT

pactl subscribe |\
    tee "$fifos/fifo1" "$fifos/fifo2" "$fifos/fifo3" >/dev/null &

acpi_listen |\
    tee "$fifos/fifo1" "$fifos/fifo2" "$fifos/fifo3" >/dev/null &

udevadm monitor --udev --property |\
    tee "$fifos/fifo1" "$fifos/fifo2" "$fifos/fifo3" >/dev/null &

( while true; do date '+%H %M %S'; sleep 1; done ) |\
    tee "$fifos/fifo1" "$fifos/fifo2" "$fifos/fifo3" >/dev/null &

statusbar.awk <"$fifos/fifo1" &
notify.awk    <"$fifos/fifo2" &
lowbat.awk    <"$fifos/fifo3"
