#!/bin/sh

# remove all bash config files
echo -n "Remove bash dotfiles from $HOME [Y/n]: "
read x

if [ "$x" = 'Y' ]
then
  [ -e ~/.bash_profile ] && rm ~/.bash_profile
  [ -e ~/.bash_login ] && rm ~/.bash_login
  [ -e ~/.bash_logout ] && rm ~/.bash_logout
  [ -e ~/.bashrc ] && rm ~/.bashrc
  [ -e ~/.bash_history ] && rm ~/.bash_history
fi

# change shell
echo -n "Change shell [Y/n]: "
read x

if [ "$x" = 'Y' ]
then
  echo
  echo 'calling sudo chsh... when asked insert something like: /bin/zsh, /bin/fish, ...'
  echo
  chsh
fi
