#!/bin/sh

# essentials
xbps-install -y curl
xbps-install -y wget
xbps-install -y unzip
xbps-install -y zsh
xbps-install -y cronie
xbps-install -y tlp

# wireless
xbps-install -y bluez
xbps-install -y NetworkManager

# xorg
xbps-install -y xorg
xbps-install -y xbacklight
xbps-install -y dunst
xbps-install -y sxhkd

# multimedia
xbps-install -y alsa-utils
xbps-install -y alsa-plugins-pulseaudio
xbps-install -y pulseaudio
xbps-install -y ncpamixer

# utilities
xbps-install -y fzf
xbps-install -y entr
xbps-install -y simple-mtpfs
xbps-install -y acpi

# programs
xbps-install -y vim-x11
xbps-install -y lf
xbps-install -y firefox
xbps-install -y mpv
xbps-install -y sxiv
xbps-install -y zathura
xbps-install -y zathura-pdf-mupdf
xbps-install -y git
xbps-install -y htop
xbps-install -y shellcheck
xbps-install -y scrot
xbps-install -y dropbox

# src dependencies
xbps-install -y base-devel
xbps-install -y libX11-devel
xbps-install -y libXinerama-devel
xbps-install -y libXft-devel
xbps-install -y libXrandr-devel

# fonts
xbps-install -y font-sourcecodepro
