#!/bin/sh

if [ "$@" = '1' ]
then

    LINK_REGEX='^https?://.*$'

    selection="$(xclip -selection primary -o)"
    link_match="$(echo "$selection" | grep -oE "$LINK_REGEX")"

    if [ -n "$link_match" ]
    then
        firefox "$link_match"
    else
        firefox "https://www.google.com/search?q=$selection"
    fi

elif [ "$@" = '2' ]
then
    selection="$(xclip -selection primary -o)"
    st -e sh -c "$selection"
fi
