#!/bin/sh

while true
do
  clock="$(date '+%H:%M')"

  batt=
  for x in /sys/class/power_supply/BAT*
  do
    if [ -n "$batt" ]
    then
      batt="$batt "
    fi

    capacity="$(cat $x/capacity)"
    status="$(cat $x/status)"

    case "$status" in
      'Discharging') status='-' ;;
      'Charging') status='+' ;;
      'Full') status='=' ;;
      *) status='?' ;;
    esac

    batt="$batt$capacity$status"
  done

  brig=
  for x in /sys/class/backlight/*
  do
    if [ -n "$brig" ]
    then
      brig="$brig "
    fi

    max="$(cat $x/max_brightness)"
    actual="$(cat $x/actual_brightness)"
    brig="$brig$((($actual * 100) / $max))*"
  done

  xsetroot -name " $brig $batt $clock "
  sleep 10
done
