#!/bin/sh
while true
do
  clock="$(date '+%H:%M %d/%m %a')"
  batt="$(cat /sys/class/power_supply/BAT0/capacity)"
  xsetroot -name " [$batt%] [$clock] "
  seconds="$(date '+%S')"
  sleep $((60 - seconds))
done
