#!/bin/sh
cd ~
mkdir Suckless
cd Suckless
git clone https://git.suckless.org/dwm
git clone https://git.suckless.org/st
git clone https://git.suckless.org/slock
git clone https://git.suckless.org/dmenu
