#!/bin/sh

# essentials
pacman -S --needed curl
pacman -S --needed wget
pacman -S --needed unzip
pacman -S --needed less
pacman -S --needed man
pacman -S --needed zip
pacman -S --needed cronie
pacman -S --needed cronie-runit
pacman -S --needed tlp
pacman -S --needed tlp-runit
pacman -S --needed zsh

# zsh
# pacman -S --needed zsh-autosuggestions
pacman -S --needed zsh-syntax-highlighting

# dbus
pacman -S --needed dbus
pacman -S --needed dbus-runit

# networking
pacman -S --needed bluez
pacman -S --needed bluez-runit
pacman -S --needed networkmanager
pacman -S --needed networkmanager-runit

# ntp
pacman -S --needed ntp
pacman -S --needed ntp-runit

# xorg
pacman -S --needed xorg
pacman -S --needed xorg-xinit
pacman -S --needed xorg-drivers
pacman -S --needed xf86-input-wacom

pacman -S --needed xclip
pacman -S --needed xsel
pacman -S --needed xdotool
pacman -S --needed dunst 
pacman -S --needed libnotify
pacman -S --needed xcompmgr
pacman -S --needed xwallpaper

# multimedia
pacman -S --needed pulseaudio-alsa
pacman -S --needed pulseaudio-bluetooth
pacman -S --needed pulseaudio-jack
pacman -S --needed pulseaudio

# acpi server
pacman -S --needed acpid
pacman -S --needed acpid-runit

# xdg
pacman -S --needed xdg-utils

# src dependencies
pacman -S --needed base-devel
pacman -S --needed go

# utilities
pacman -S --needed fzf
pacman -S --needed entr
pacman -S --needed acpi

# programs
pacman -S --needed neovim
pacman -S --needed python
pacman -S --needed python-pynvim
pacman -S --needed aspell
pacman -S --needed aspell-en
pacman -S --needed aspell-es
pacman -S --needed librewolf
pacman -S --needed speech-dispatcher
pacman -S --needed mpv
pacman -S --needed sxiv
pacman -S --needed zathura
pacman -S --needed zathura-ps
pacman -S --needed zathura-djvu
pacman -S --needed zathura-pdf-poppler
pacman -S --needed git
pacman -S --needed htop
pacman -S --needed pavucontrol
pacman -S --needed alacritty
pacman -S --needed gnome-keyring
pacman -S --needed seahorse

# fonts
pacman -S --needed ttf-hack
pacman -S --needed ttf-dejavu
pacman -S --needed ttf-liberation
pacman -S --needed noto-fonts-cjk
pacman -S --needed noto-fonts-emoji
pacman -S --needed ttf-joypixels
pacman -S --needed ttf-fira-mono
pacman -S --needed ttf-cascadia-code
pacman -S --needed ttf-jetbrains-mono
pacman -S --needed ttc-iosevka

# Para que nerdtree funcione.
pacman -S --needed ttf-sourcecodepro-nerd
pacman -S --needed ttf-go-nerd
pacman -S --needed ttf-inconsolata-go-nerd
pacman -S --needed ttf-hack-nerd
pacman -S --needed ttf-jetbrains-mono-nerd
pacman -S --needed ttf-iosevka-nerd
