#!/bin/sh

yay -S --noconfirm --needed lf-bin
yay -S --noconfirm --needed simple-mtpfs
yay -S --noconfirm --needed dragon-drag-and-drop
yay -S --noconfirm --needed posix-manpages
yay -S --noconfirm --needed selectdefaultapplication-git
