#!/bin/sh

# installar opam
#
# opam gestiona instalacciones de ocaml, es parecido a un venv de python.
#
# opam instala en el home directory distinatas versiones del compilador de ocaml, cada una de ellas se le llama
# switch, y atravez de opam instala dependencias para cada switch.
#
# Los compandos siguientes instalan ocaml y dependencias para el switch por defecto llamado default en la carpeta 
# de usuario en ~/.opam/default.
#
# El compilador de ocaml busca dependencias en ciertas subcarpetas del switch actual, opam maneja e installa 
# paquetes en estos directorios de forma tal que el compilador conoce de su existencia.
sudo pacman --needed -S opam

# Configura una instalaicion de ocaml en ~/.opam.
opam init
eval $(opam env)

# Installs the latest versions of the packages.
#
# Dune es una build tool de ocaml. Basicamente define stanzas, que son como reglas de compilacion conocidas.
#
# Dune realiza estas tareas utilizando el compilador encontrado en el PATH, es decir el switch actual.
opam install dune
opam install utop
opam install ocaml-lsp-server
opam install ocamlformat
opam install ocaml-manual
opam install odig

# add repos.
opam repo add rocq-released 'https://rocq-prover.org/opam/released'

# install and pin rocq dependencies to a specific version.
opam pin add rocq-runtime '9.1.1'
opam pin add rocq-core '9.1.1'
opam pin add rocq-stdlib '9.1.0'

# finally install rocq-prover metapackage with its dependencies pinned to a particular version.
opam install rocq-prover
