#!/bin/sh

# utilities
pacman -S --noconfirm --needed fzf
pacman -S --noconfirm --needed entr
pacman -S --noconfirm --needed acpi
pacman -S --noconfirm --needed tree
pacman -S --noconfirm --needed clipnotify
pacman -S --noconfirm --needed poppler
pacman -S --noconfirm --needed highlight
pacman -S --noconfirm --needed pdfgrep

# programs
pacman -S --noconfirm --needed slock
pacman -S --noconfirm --needed neovim
pacman -S --noconfirm --needed kakoune
pacman -S --noconfirm --needed kak-lsp
pacman -S --noconfirm --needed aspell
pacman -S --noconfirm --needed aspell-en
pacman -S --noconfirm --needed aspell-es
pacman -S --noconfirm --needed firefox
pacman -S --noconfirm --needed mpv
pacman -S --noconfirm --needed sxiv
pacman -S --noconfirm --needed zathura
pacman -S --noconfirm --needed zathura-pdf-mupdf
pacman -S --noconfirm --needed zathura-ps
pacman -S --noconfirm --needed git
pacman -S --noconfirm --needed htop
pacman -S --noconfirm --needed maim
pacman -S --noconfirm --needed pavucontrol
pacman -S --noconfirm --needed tig
pacman -S --noconfirm --needed pacman-contrib
pacman -S --noconfirm --needed alacritty
pacman -S --noconfirm --needed newsboat
pacman -S --noconfirm --needed gnome-keyring
pacman -S --noconfirm --needed seahorse

# lsps
pacman -S --noconfirm --needed texlab

# fonts
pacman -S --noconfirm --needed ttf-hack
pacman -S --noconfirm --needed terminus-font
pacman -S --noconfirm --needed ttf-dejavu
pacman -S --noconfirm --needed ttf-linux-libertine
pacman -S --noconfirm --needed ttf-liberation
pacman -S --noconfirm --needed noto-fonts
pacman -S --noconfirm --needed noto-fonts-emoji
pacman -S --noconfirm --needed noto-fonts-extra
pacman -S --noconfirm --needed ttf-joypixels
pacman -S --noconfirm --needed otf-ipafont
