#!/bin/sh

# El compilador de ghc funciona similar al de ocaml (ver packages_coq_ocaml). Tiene definido
# rutas donde busca codigo de librerias, estas rutas son relativas a la instalacion de ghc, 
# similar a como ocaml y python funcionan.
#
# Cabal es la herramienta oficial de ghc para el manejo de paquetes, y ademas es una build tool
# al mismo tiempo. Instala paquetes de repos en las rutas de ghc y define archivos .cabal con los 
# cuales uno puede definir como instalar un proyecto a partir de su codigo fuente. 
#
# ghcup es un toolchain manager for Haskell, basicamente es igual a opam o a python venv, maneja 
# instalaciones del compilador en el directorio home de cada usuario y permite instalar paquetes 
# para cada compilador or environment configurado.
#
# Por defecto ghcup instala ejecutables en ~/.ghcup/bin. Se necesita agregar al path esta carpeta.

# instalar ghcup
yay -S ghcup-hs-bin

# instalar ghc, cabal y lsp en home.
ghcup install ghc
ghcup install cabal
ghcup install hls

# utilizar ghc, cabal y lsp en home.
ghcup set ghc
ghcup set cabal
ghcup set hls
