#!/bin/sh

# setup acpid service
systemctl enable acpid

# setup cronie service
systemctl enable cronie

# setup bluez service
systemctl enable bluetooth

# setup NetworkManager service
systemctl enable NetworkManager

# setup openntp services
systemctl enable openntpd

# setup tlp service
systemctl enable tlp
