#!/bin/sh

# setup acpid service
pacman --noconfirm --needed -S acpid-runit
ln -s /etc/runit/sv/acpid /run/runit/service

# setup cronie service
pacman --noconfirm --needed -S cronie-runit
ln -s /etc/runit/sv/cronie /run/runit/service

# setup connman service
pacman --noconfirm --needed -S connman-runit
ln -s /etc/runit/sv/connmand /run/runit/service

# setup openntp services
pacman --noconfirm --needed -S openntpd-runit
ln -s /etc/runit/sv/openntpd /run/runit/service

# setup tlp service
pacman --noconfirm --needed -S tlp-runit
ln -s /etc/runit/sv/tlp /run/runit/openntpd
