#!/bin/sh

# setup acpid service
ln -s /etc/runit/sv/acpid /run/runit/service

# setup cronie service
ln -s /etc/runit/sv/cronie /run/runit/service

# setup network manager service
ln -s /etc/runit/sv/NetworkManager /run/runit/service

# setup openntp services
ln -s /etc/runit/sv/ntpd /run/runit/service

# setup tlp service
ln -s /etc/runit/sv/tlp /run/runit/openntpd
