#!/bin/sh

# https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html
mkdir -p /usr/local/src
cd /usr/local/src

# clone suckless programs
git clone https://git.suckless.org/dwm
# git clone https://git.suckless.org/st
git clone https://git.suckless.org/dmenu
git clone https://git.suckless.org/slock
