#!/bin/sh

if ! cat /etc/group | grep -q '^bluetooth:'
then
    echo 'Group bluetooth not found, bluez not installed!'
    exit 1
fi

me="$(whoami)"

if [ -z "$me" ]
then
    echo "User is empty! (whoami is not working?)"
    exit 1
fi

if [ "$me" = "root" ]
then
    echo "Run script without sudo"
    exit 1
fi

sudo usermod -a -G bluetooth "$me"
